[package]
name = "cln-trace"
version = "0.1.0"
edition = "2021"

[dependencies]
libbpf-rs = "0.24.2"
tokio = { version = "1.39.3", features = ["rt-multi-thread", "sync"] }

[build-dependencies]
libbpf-cargo = "0.24.2"